mark some sharedutilities test to skip
ni/niveristand-aim-milStd1553-custom-device pull request #112
Opened 2024-04-01 04:13 UTC by ashukumaNI

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-aim-milStd1553-custom-device/blob/main/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-aim-milStd1553-custom-device/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

These tests are failing since 23.8. These tests must be disabled as:

Issue is not reproducible, identical tests are passing in other repo. After discussion we decided to mark these tests to skip.

### Why should this Pull Request be merged?

Skip some sharedutilities test in ATS runs.

### Implementation
Switch to Disable.
![pr](https://github.com/ni/niveristand-aim-milStd1553-custom-device/assets/125341406/5d2aac0b-1464-487d-a5da-29ab41610e77)

### What testing has been done?

2024-04-01 15:44 UTC, buckd requested changes
At some point, all of the custom device source should be mass compiled to LV 2021 as that is the oldest supported version, but that should be a different PR. To just disable the tests to get clean test results, you can make this change in LV 2021, but also update the README to state that the source now requires LV 2021.

2024-04-01 15:44 UTC, buckd commented on Source/Custom Device Support/Tests/Unit/Shared/SharedUtilities/SharedUtilities.lvclass
This change should not require any updates the `.lvclass` file as it is only enabling a different diagram of VIs. This needs to be reverterd.

It also shows that this change is made in LV 2024. This will not work because we will then not be able to build this custom device for older versions of VeriStand that we still support. The source for this repo is still in LV 2020, although that version is no longer supported. This change needs to be made in LV 2021.

2024-04-02 09:21 UTC, ashukumaNI commented on Source/Custom Device Support/Tests/Unit/Shared/SharedUtilities/SharedUtilities.lvclass
Reverted previous changes. Edited the test files using LV2021. Updated Readme.

2024-04-02 13:32 UTC, buckd approved these changes

2024-04-02 13:42 UTC, merged